version: 1.0.{build}

platform:
    - MinGW_x86
    - MinGW_x64
    - MSVC_2013_x86
    - MSVC_2013_x64
    - MSVC_2015_x86
    - MSVC_2015_x64

install:
    - scripts\ci-pre.cmd

build_script:
    - scripts\ci-build.cmd

test_script:
    - scripts\ci-test.cmd
